export const ADD_TODO = "ADD_TODO";
export const UPDATE_TODO = "UPDATE_TODO";
export const DELETE_TODO = "DELETE_TODO";
export const TOGGLE_TODO_COMPLETED = "TOGGLE_TODO_COMPLETED";

export const TOGGLE_EXPAND_COMPLETED = "TOGGLE_EXPAND_COMPLETED";
